# Generated by Django 5.0.7 on 2024-08-01 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='live_news_db',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_time', models.DateTimeField()),
                ('company_name', models.CharField(max_length=200)),
                ('ticker', models.CharField(default='Not Available', max_length=200)),
                ('news_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=2000)),
                ('body', models.CharField(max_length=200)),
                ('pdf_url', models.CharField(default='Not Available', max_length=500)),
                ('bse_page_url', models.CharField(default='Not Available', max_length=500)),
                ('full_text', models.TextField(default='')),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
