# Generated by Django 5.0.7 on 2024-08-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_taskcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickers', models.CharField(default='', max_length=20000)),
                ('user_email', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
