# Generated by Django 5.0.7 on 2024-08-01 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recent_trades_db',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deal_date', models.DateTimeField()),
                ('security_code', models.IntegerField()),
                ('company', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=500)),
                ('deal_type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('industry', models.CharField(blank=True, max_length=500, null=True)),
                ('sector', models.CharField(blank=True, max_length=500, null=True)),
                ('dtype_db', models.IntegerField(default=2)),
            ],
        ),
    ]
